channels:
  - conda-forge
  - default
dependencies:
  - python=3.6.9
  - cython
  - r-base
  - pip
  - pip:
    - jupyter
    - jupyterlab
    - graphviz
    - matplotlib
    - seaborn
    - sklearn
    - numpy
    - pandas
    - jupyter_server_proxy
    - rpy2
