channels:
  - conda-forge
  - default
dependencies:
  - python=3.6.9
  - pandas=0.25.3
  - cython
  - pip
  - pip:
    - jupyter
    - jupyterlab
    - graphviz
    - matplotlib
    - seaborn
    - sklearn
    - numpy
